"""
Dream Machine — Export Engine
PDF and Markdown export for blueprints.
"""
import io
from datetime import datetime


def export_markdown(blueprint: dict) -> str:
    """Convert a blueprint dict to formatted Markdown."""
    sections = blueprint.get("sections", {})
    idea = blueprint.get("idea", "")
    idea_type = blueprint.get("idea_type", "")
    created = blueprint.get("created_at", "")[:10]

    lines = [
        f"# {blueprint.get('title', idea[:60])}",
        f"> **Type:** {idea_type} | **Created:** {created}",
        "",
        f"**Original Idea:** {idea}",
        "",
        "---",
        "",
    ]

    section_titles = {
        "executive_summary": "📋 Executive Summary",
        "user_personas": "👥 User Personas",
        "core_features": "⚡ Core Feature List",
        "architecture": "🏗️ Architecture Map",
        "tech_stack": "🔧 Tech Stack",
        "roadmap": "🗓️ Roadmap",
        "business_model": "💰 Business Model",
        "risk_analysis": "⚠️ Risk Analysis",
        "competitor_landscape": "🏁 Competitor Landscape",
        "success_metrics": "📊 Success Metrics",
    }

    for key, title in section_titles.items():
        content = sections.get(key, "")
        if content:
            lines.append(f"## {title}")
            lines.append("")
            lines.append(content)
            lines.append("")
            lines.append("---")
            lines.append("")

    lines.append(f"*Generated by Dream Machine — {datetime.now().strftime('%Y-%m-%d %H:%M')}*")
    return "\n".join(lines)


def export_pdf_bytes(blueprint: dict) -> bytes:
    """Generate a PDF from the blueprint using ReportLab."""
    try:
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Table, TableStyle
        )
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.colors import HexColor, black, white
        from reportlab.lib.units import mm
        from reportlab.lib.enums import TA_LEFT, TA_CENTER
        import re as _re

        buf = io.BytesIO()

        # Page setup
        doc = SimpleDocTemplate(
            buf,
            pagesize=A4,
            leftMargin=20 * mm,
            rightMargin=20 * mm,
            topMargin=20 * mm,
            bottomMargin=20 * mm,
        )

        # Colors
        PRIMARY = HexColor("#5C6BFF")
        ACCENT = HexColor("#00F5D4")
        DARK = HexColor("#0A0A12")
        MUTED = HexColor("#6B6B8A")
        TEXT = HexColor("#1A1A2E")

        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            "DreamTitle",
            parent=styles["Title"],
            fontSize=28,
            fontName="Helvetica-Bold",
            textColor=PRIMARY,
            spaceAfter=4,
            spaceBefore=0,
        )
        subtitle_style = ParagraphStyle(
            "DreamSubtitle",
            parent=styles["Normal"],
            fontSize=11,
            fontName="Helvetica",
            textColor=MUTED,
            spaceAfter=20,
        )
        section_title_style = ParagraphStyle(
            "SectionTitle",
            parent=styles["Heading2"],
            fontSize=14,
            fontName="Helvetica-Bold",
            textColor=PRIMARY,
            spaceBefore=16,
            spaceAfter=8,
        )
        body_style = ParagraphStyle(
            "DreamBody",
            parent=styles["Normal"],
            fontSize=10,
            fontName="Helvetica",
            textColor=TEXT,
            leading=16,
            spaceAfter=6,
        )

        def clean(text):
            """Strip markdown for PDF."""
            text = _re.sub(r"\*\*(.+?)\*\*", r"\1", text)
            text = _re.sub(r"\*(.+?)\*", r"\1", text)
            text = _re.sub(r"#{1,6}\s*", "", text)
            text = _re.sub(r"\|.+\|", "", text)
            text = _re.sub(r"-{3,}", "", text)
            return text.strip()

        story = []

        # Header
        story.append(Paragraph("✦ Dream Machine", subtitle_style))
        story.append(Paragraph(blueprint.get("title", blueprint.get("idea", "")[:60]), title_style))
        meta = f"Type: {blueprint.get('idea_type', '')}  |  Generated: {datetime.now().strftime('%B %d, %Y')}"
        story.append(Paragraph(meta, subtitle_style))
        story.append(HRFlowable(width="100%", thickness=2, color=PRIMARY))
        story.append(Spacer(1, 12))

        idea_label = ParagraphStyle("IdeaLabel", parent=body_style, textColor=MUTED, fontSize=9)
        story.append(Paragraph("ORIGINAL IDEA", idea_label))
        story.append(Paragraph(blueprint.get("idea", ""), body_style))
        story.append(Spacer(1, 12))
        story.append(HRFlowable(width="100%", thickness=0.5, color=HexColor("#DDDDEE")))

        # Sections
        section_titles = {
            "executive_summary": "📋 Executive Summary",
            "user_personas": "👥 User Personas",
            "core_features": "⚡ Core Feature List",
            "architecture": "🏗️ Architecture Map",
            "tech_stack": "🔧 Tech Stack",
            "roadmap": "🗓️ Roadmap",
            "business_model": "💰 Business Model",
            "risk_analysis": "⚠️ Risk Analysis",
            "competitor_landscape": "🏁 Competitor Landscape",
            "success_metrics": "📊 Success Metrics",
        }

        sections = blueprint.get("sections", {})
        for key, title in section_titles.items():
            content = sections.get(key, "")
            if not content:
                continue

            story.append(Paragraph(title, section_title_style))
            story.append(HRFlowable(width="100%", thickness=0.5, color=ACCENT))
            story.append(Spacer(1, 6))

            for line in content.split("\n"):
                line = line.strip()
                if not line:
                    story.append(Spacer(1, 4))
                    continue
                clean_line = clean(line)
                if clean_line:
                    story.append(Paragraph(clean_line, body_style))

            story.append(Spacer(1, 8))

        # Footer
        story.append(HRFlowable(width="100%", thickness=1, color=PRIMARY))
        story.append(Spacer(1, 6))
        footer_style = ParagraphStyle("Footer", parent=body_style, fontSize=9,
                                      textColor=MUTED, alignment=TA_CENTER)
        story.append(Paragraph(
            f"Generated by Dream Machine | {datetime.now().strftime('%Y-%m-%d %H:%M')} | dreamachine.ai",
            footer_style
        ))

        doc.build(story)
        return buf.getvalue()

    except ImportError:
        # ReportLab not available — return markdown as bytes
        md = export_markdown(blueprint)
        return md.encode("utf-8")
    except Exception as e:
        md = f"# Export Error\n\nCould not generate PDF: {e}\n\n" + export_markdown(blueprint)
        return md.encode("utf-8")
